name: Rust CI
on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  Checks:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: linter
        run: cargo check
      - name: run unit tests
        run: cargo test --verbose
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
